### ISSUE TITLE
Binding emmet to something else then C-z

### ISSUE THREAD

**Issue by jwoudenberg** [jwoudenberg/brangelina#18]
Are you okay with setting the emmet leader key to something else then C-z? I use that quite often to suspend the vim process and return me to the shell.

**Comment by stoeffel** [comment]
It actually turns out that I never use emmet 😆

**Comment by jwoudenberg** [comment]
Hahaha, for me that happens with about two thirds of the vim plugins I install :). You want to remove it?

**Comment by stoeffel** [comment]
yes, let's remove it.

**Comment by jwoudenberg** [comment]
Done!
