### ISSUE TITLE
Make fzf preview configurable

### ISSUE THREAD

**Issue by jwoudenberg** [jwoudenberg/brangelina#46]
I'd like to get rid of the fzf preview in my configuration. I find that I do not use it, but it takes up a lot of space. I'm not sure what might be the best way to make it configurable, or if there would be a way I can redefine the command in my local .vimrc to overwrite its behavior. If anyone has any ideas they would be appreciated!

**Comment by stoeffel** [comment]
makes sense. could we just add two different configs and define a flag which we then use to branch in brangelina?

**Comment by stoeffel** [comment]
we've removed the preview
