### ISSUE TITLE
terminal improvements

### ISSUE THREAD

**Issue by stoeffel** [jwoudenberg/brangelina#51]
This is a collection of things that I want to improve re terminal integration some day:

- [x] I have to press fzf mappings twice
- [ ] anything that opens vim in a terminal should use the host instance instead of nesting vims.

**Comment by jwoudenberg** [comment]
For reference: I don't have that first issue, but it sounds horrible.

That second point would be completely awesome.

**Comment by stoeffel** [comment]
1. might be a onivim thing

**Comment by stoeffel** [comment]
I think a nice binding for `AsyncRun` would be cool. I think in general it's better to run commands through that. or using `:T`

**Comment by stoeffel** [comment]
re 1: I had to add `let $FZF_DEFAULT_OPTS .= ' --no-height'` to my init.vim. Maybe  this doesn't happen to you because I'm on neovim nightly. https://github.com/junegunn/fzf/issues/809
